#!/bin/bash
# refresh-env.sh — writes /opt/nsq-platform/.env from SSM Parameter Store.
#
# This file is the single source of truth for the env refresh. It used to be
# generated by terraform/user_data.sh.tpl as a heredoc, which meant the copy
# in git and the copy on the box could (and did) drift apart — a `git pull`
# on the instance would overwrite the working script. user_data now only
# writes the small config file this script reads, so `git pull` is safe.
#
# Config comes from /etc/nsq-platform.conf (written by user_data at first
# boot):
#     AWS_REGION=ap-south-1
#     REDIS_URL_PARAM=/nsq-platform/prod/redis_url
#     GEMINI_KEY_PARAM=/nsq-platform/prod/gemini_api_key
#
# If that file is absent (local dev, or a box provisioned by hand) the script
# leaves any existing .env alone and exits 0, so deploy.sh still works.
set -euo pipefail

APP_DIR=${APP_DIR:-/opt/nsq-platform}
CONF=${NSQ_PLATFORM_CONF:-/etc/nsq-platform.conf}

if [ ! -r "$CONF" ]; then
  echo "refresh-env: no $CONF — leaving $APP_DIR/.env as-is." >&2
  exit 0
fi

# shellcheck source=/dev/null
. "$CONF"

: "${AWS_REGION:?AWS_REGION missing from $CONF}"
: "${REDIS_URL_PARAM:?REDIS_URL_PARAM missing from $CONF}"
: "${GEMINI_KEY_PARAM:?GEMINI_KEY_PARAM missing from $CONF}"

cd "$APP_DIR"

# KMS-decrypted via the instance's IAM role (see terraform/iam.tf).
REDIS_URL=$(aws ssm get-parameter \
  --name "$REDIS_URL_PARAM" --with-decryption \
  --region "$AWS_REGION" --query 'Parameter.Value' --output text)

GEMINI_API_KEY=$(aws ssm get-parameter \
  --name "$GEMINI_KEY_PARAM" --with-decryption \
  --region "$AWS_REGION" --query 'Parameter.Value' --output text)

# The "unset" sentinel in secrets.tf is a single space — collapse it back to
# empty so docker-compose.yml's GEMINI_API_KEY=${GEMINI_API_KEY:-} still
# behaves as "offline heuristic engine" when nothing was provided.
GEMINI_API_KEY="$(echo "$GEMINI_API_KEY" | xargs || true)"

# Written atomically: a half-written .env would take the whole stack down on
# the next `docker compose up`.
umask 077
cat > .env.tmp <<ENV_EOF
REDIS_URL=$REDIS_URL
GEMINI_API_KEY=$GEMINI_API_KEY
ENV_EOF
mv .env.tmp .env
chmod 600 .env
echo "refresh-env: wrote $APP_DIR/.env from SSM ($AWS_REGION)."
